### PR TITLE
[pygw] add alignment visualizer tool

### PR DESCRIPTION
**Pull request by tijyojwad**
adding a small tool to visualize cigar strings for pairwise alignments

### CODE REVIEW

**Comment by tijyojwad** [comment]
@o8191 Can you have a look at why the CentOS 7 job failed? Appears to be an issue with installing lumpy, but that seems odd...

**Comment by o8191** [comment]
> @o8191 Can you have a look at why the CentOS 7 job failed? Appears to be an issue with installing lumpy, but that seems odd...

It seems this issue started to happen since we updated our images in docker hub:
https://gpuci.gpuopenanalytics.com/job/clara-genomics/job/gpuci/job/clara-genomics-analysis/job/branches/job/clara-genomics-analysis-branch-pipeline/
I'm looking into it

**Comment by o8191** [comment]
- The `centos7` failed test is resolved in https://github.com/clara-parabricks/gpuci-build-environment/pull/11
- The `ubuntu16.04-cuda9.0` test is due to us using Python 3.5 in that image (which we dropped the support and doesn't have this matplotlib version available in PyPI) and should be resolved once we merge the new configuration in https://github.com/rapidsai/gpuci-scripts/pull/313/files#diff-6d26146b48f1462a5b5108bd0506660b6869472d60cfdf75e66c139f534c2e68L79

**Comment by o8191** [comment]
rerun tests

**Comment by o8191** [comment]
rerun tests

**Comment by o8191** [comment]
rerun tests

**Pull request merged**
