### PR TITLE
[common] Fixed a compiler warnings and a problem with CUDA 11

### PR DESCRIPTION
**Pull request by ahehn-nv**
Hotfix for #554 and experimental CUDA 11 support.

### CODE REVIEW

**Comment by ahehn-nv** [comment]
@tijyojwad In order to not have too many hotfix releases, we might want to combine this with a fix for CUDA 11.
I don't have time to work on that right now, but I'm happy to merge a PR against my branch.

**Comment by tijyojwad** [comment]
agreed, @ahehn-nv - @atadkase can you create a quick PR with the fix to enable CUDA 11 into this branch? We decided to make the `gw_cuda_gen_all_arch` `OFF` by default in CMakeLists.txt. This would need an update to the CMakeLists.txt and a change to `ci/common/build-test-sdk.sh` with line 30 updated to include `gw_cuda_gen_all_arch=ON`. Was there anything else that's needed to enable CUDA 11?

**Review by tijyojwad — APPROVED** [review]

**Comment by ahehn-nv** [comment]
@tijyojwad Are we sure these changes won't break the python packages - if we only compile for one architecture by default?

**Comment by tijyojwad** [comment]
> @tijyojwad Are we sure these changes won't break the python packages - if we only compile for one architecture by default?

Glad you mentioned this again. I was under the impression the build-test-sdk.sh update took care of cmake flags for python builds as well, but then I double checked and it was actually in a different place. So I just pushed a fix for that. Thanks for bringing it up!

**Pull request merged**
