### PR TITLE
Renamed the asynchronous version of device_copy_n

### PR DESCRIPTION
**Pull request by EpiSlim**
Fixes issue #541

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by ahehn-nv — APPROVED** [review]
Looks good, thanks!

**Comment by ahehn-nv** [comment]
add to allowlist

**Comment by tijyojwad** [comment]
add to allowlist

**Review by ahehn-nv — APPROVED** [review]

**Pull request merged**
